### ISSUE TITLE
Add DSL verb for `download`.

### ISSUE THREAD

**Issue by holetse** [labzero/bootleg#141]
Downloading a file from the remote host can be done by using `Bootleg.SSH.download/3`, but its usage is undocumented and it requires a raw SSHKit.Context. Exposing this functionality via the DSL with proper role/host support is a much better alternative.

```elixir
use Bootleg.Config

after_task :deploy do
  # dumps to the remote workspace
  download :app, "path/to/a/remote/file"

  # or with an explicit destination
  download :app, "path/to/a/remote/file", "local/path"
end
```

**Comment by rjanja** [comment]
I'm thinking for both upload and download tasks, but probably more important for download, where a role may correspond to more than one host, it could be helpful to be able to supply a role filter for`%Bootleg.Host` options that must match.

```elixir
download [:app, primary: true], "path/to/a/migration/log", "local/artifacts"
```

**Comment by holetse** [comment]
You bring up a good point.. what do we do if multiple hosts match, and they all return a file with the same name? Do we error? Last file wins? Add a suffix or directory indicating the origin?

**Comment by brienw** [comment]
If multiple hosts return a file with the same name, my preference is we don't do anything to try and resolve it. Just let SSHKit do what it will - currently the SSHKit behavior is that the last file that lands wins. If we ever want to do anything different, we should consult the SSHKit team and get their thoughts. I believe any change in behavior would be best to do in SSHKit instead of bootleg

**Comment by rjanja** [comment]
Is there a use case for trying to download the same thing from more than one host?

E.g.:
* One host fails to transfer the file, for whatever reason, but another does so successfully
* A directory is supplied for the remote path, and each host is asked for all of the (recursive) contents of that path
* ...other examples?

I would advocate for either limiting the hosts to the first one that matches the role specified, or throwing an error, unless the remote path ends in a "/". We shouldn't need to refer to SSHKit documentation to find out the expected behavior.
