### ISSUE TITLE
Task Hook not running in right order

### ISSUE THREAD

**Issue by bitboxer** [labzero/bootleg#294]
This week I updated bootleg in [SignDict](https://github.com/signdict/website) and discovered that in the latest version it doesn't correctly execute stuff in `after_task` hooks. I have a `after_task(:compile, :phoenix_digest)` that creates the assets, but sadly it is run after the release is build. One step too late. This means the javascript is build after the release is build and thus is not included. The deployed server doesn't have any assets and is damaged.

Is this a known bug? Is this project still maintained?

**Comment by derekkraan** [comment]
I have also been having this problem. Based on my tests, I believe it to be fixed in `master`. Specifically, I think it might be this commit: https://github.com/labzero/bootleg/commit/00039dd4277c55210607d154196ce8222552e297 (although I can't actually pinpoint why it was broken or why this commit fixed it, but I see the issue in release 0.10.0, but not on current master HEAD).

Hope this helps!

Derek

**Comment by bitboxer** [comment]
I am currently switching all my projects to a docker approach of deployment because I haven't seen any progress or communication here 😭

**Comment by derekkraan** [comment]
Totally understandable.

**Comment by rjanja** [comment]
Thanks for the feedback, it looks like this was overlooked after being fixed in https://github.com/labzero/bootleg/commit/483d3f63ad5f451c51e77c053a31905a0f455c66. We'll get a new package published shortly.

**Comment by bitboxer** [comment]
Awesome. Thanks for commenting here 🥰.

**Comment by bitboxer** [comment]
If you need any help, i would love to donate a couple of my hours to your project

**Comment by brienw** [comment]
⚡️ new package `0.11.0` pushed up to hex. thanks for bumping this thread @derekkraan and @bitboxer! this one slipped through the cracks as we were busy on other projects
